run:
  go: '1.22.5'

issues:
  exclude-dirs:
    - vendor
    - third_party
    - go/pkg/mod
  # exclude-files:
  #   - ".*_test.go"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - typecheck
    - unused
    - gocyclo
    - goconst
    # - gocognit # Diabling for now
    - gocritic