version: 2
builds:
  - main: ./cmd/mockthis/

brews:
  - name: mockthis
    homepage: https://mockthis.io
    description: Mock API endpoints for testing and development.
    license: MIT
    install: go install ./cmd/mockthis
    directory: Formula
    repository:
      owner: nicobistolfi
      name: homebrew-carbon
      branch: main
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    commit_author:
      name: nicobistolfi
      email: git@bistol.fi
