version: 2
builds:
  - main: ./cmd/mockthis/
    binary: mockthis

brews:
  - name: mockthis
    homepage: https://mockthis.io
    description: Mock API endpoints for testing and development.
    license: MIT
    install: bin.install "mockthis"
    directory: Formula
    repository:
      owner: nicobistolfi
      name: homebrew-carbon
      branch: main
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    commit_author:
      name: nicobistolfi
      email: git@bistol.fi
    test: |
      system "#{bin}/mockthis version"
